### PR TITLE
Update to v18.6.0

### PR DESCRIPTION
**Pull request by synapticarbors**

### CODE REVIEW

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@conda-forge/core I couldn't find an issue related to the error:

```
+ conda build /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_.yaml --quiet
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2155, in build_tree
    bypass_env_check=True)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 734, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/variants.py", line 503, in get_package_variants
    combined_spec, extend_keys = combine_specs(specs, log_output=config.verbose)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/variants.py", line 263, in combine_specs
    log_output=log_output)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/variants.py", line 197, in _combine_spec_dictionaries
    values[k].extend(ensure_list(v))
AttributeError: 'collections.OrderedDict' object has no attribute 'extend'
Exited with code 1
```

Is there an open issue out there for this that I'm missing or does anyone know the solution already?

**Comment by isuruf** [comment]
https://github.com/conda-forge/conda-smithy/issues/811

**Comment by synapticarbors** [comment]
@conda-forge-admin, please rerender

**Comment by synapticarbors** [comment]
@conda-forge-admin, please lint

**Comment by synapticarbors** [comment]
@conda-forge/core - Can anyone spot what's going on with the linter here? I tried re-copying the maintainers section over from the example meta.yaml, but it looked the same and still failed.

**Comment by ocefpaf** [comment]
I guess that is a bug in latest conda-smithy. I can lint that with the older version just fine.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/conda-smithy/issues/876

**Pull request merged**
